name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        # Use "yarn install" and "yarn build" if you're using Yarn for package management

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # Change this to the branch you want to deploy to (e.g., gh-pages)
          FOLDER: target/dist # Specify the correct folder where your built Vue.js application resides

